### ISSUE TITLE
MySQL 23000 Error on Installation process 

### ISSUE THREAD

**Issue by aityahiaidir** [cboulanger/bibliograph#192]
Hello,

I am trying to install bibliograph, but, when installing the application i get a SQLSTATE[23000] MySQL Error, Integrity constraint :1048 column modified can not be null.

**Comment by cboulanger** [comment]
Hi. What PHP and MySQL versions are your using? And did you use the current master or a release?

**Comment by aityahiaidir** [comment]
il use a Laragon server with  MySQL 5.7.19 and PHP 7.1.17
tables generated in the database bibliograph_admin have the field "modified" NULL attribut as false and there is no timestamp value generated when a row are inserted.

**Comment by aityahiaidir** [comment]
I changed the PHP version to 5.6 according to recommendation,and issue still remaining the same, with MySQL 5.7

**Comment by cboulanger** [comment]
Can you downgrade to an earlier MySQL version? I know Bibliograph has an issue with newer MySQL versions because they are much more strict on the schema. Of course, if you can find a fix that would make it work with 5.7, it would be even better...

**Comment by cboulanger** [comment]
Timestamp definition is here: https://github.com/cboulanger/bibliograph/blob/master/bibliograph/services/class/qcl/data/db/adapter/PdoMysql.php#L806

Can't do much at the moment - I am on vacation :-)
